import Scene from "@components/threejs/TestScene";


import '@styles/globals.css'
import localFont from 'next/font/local';

const jura = localFont({ 
  src: './static-fonts/Jura-Regular.ttf',
  variable: '--font-jura', 
});

const thermidava = localFont({ 
  src: './static-fonts/Thermidava Regular.ttf',
  variable: '--font-thermadiva', 
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jura.variable} ${thermidava.variable} font-sans h-full`}>
      <body className="h-full bg-gray-950">
        {children}
      </body>
    </html>
  )
}
