import { Analytics } from "@vercel/analytics/react"

import "@/styles/globals.css"
import localFont from 'next/font/local'

const jura = localFont({ 
  src: '/static_fonts/Jura-Regular.ttf',
  variable: '--font-jura', 
});

const thermidava = localFont({ 
  src:  '/static_fonts/Thermidava Regular.ttf'  /* '@/ static_fonts/Thermidava Regular.ttf' */,
  variable: '--font-thermidava', 
});

const gilgan = localFont({ 
  src: '/static_fonts/Gilgan-Regular.ttf',
  variable: '--font-gilgan', 
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jura.variable} ${thermidava.variable} ${gilgan.variable} font-sans h-full`}>
      <body>{children}</body>
    </html>
  )
}
